### ISSUE TITLE
Enhancement suggestion: read through file just once

### ISSUE THREAD

**Issue by stoerr** [atw31337/donkey#1]
Nicely written! If you have fun improving it: It currently does read through the file twice, which would be a problem in large files as [e.g. in logfiles](https://superuser.com/questions/543950/opposite-of-tail-all-lines-except-the-last-n-lines). That is not really necessary - you could also buffer the last n lines in a queue and always output just the line read n lines ago when reading a line. If you stop after the file was read through, that does the right thing.

**Comment by atw31337** [comment]
Thank you. This was my first Python script. I've been looking for a reason to start using Python and this seemed like a good application. The first read through simply counts the lines and doesn't take nearly as long as the second read through. I tested this script on a file containing close to 33 million lines and it took approximately 30 to 40 seconds. I like your buffering idea. I had not thought of that. I will re-code it and test it out so see how much faster it gets.

**Comment by atw31337** [comment]
I had another consideration regarding the buffer method. The size of the buffer would be dependent on -n; therefore, the buffer size would be variable. If a very large number, say 20 million, were to be used with the -n option, this may cause serious memory issues. I think the best way to avoid this issue would be to vary the method utilized based on the size of -n and a maximum buffer size. Thoughts?

**Comment by atw31337** [comment]
In order to avoid memory related issues, I rewrote the script to use the line count method with high n values and a buffering method with lower n values; however, after testing against a very large file, the original line count method is still faster. It seems the buffer management overhead outweighs the line count overhead
